### PR TITLE
add paper 'Let Me Choose: From Verbal Context to Font Selection'

### PR DESCRIPTION
**Pull request by wantuashley**
add one more paper Let Me Choose: From Verbal Context to Font Selection

### CODE REVIEW

**Comment by zhuojg** [comment]
`Let Me Choose` have been added😂. Maybe you can find another one.
Besides, `arXiv`  is a free distribution service and an open-access archive for scholarly articles, it should NOT be in the column `Publication`. `Publication` should be **conference**(e.g., CVPR, AAAI) or **journal** where the paper was published.

**Comment by harrywang** [comment]
@zhuojg I think 'arXiv` link is OK too and agree with your other comments. This PR has conflicts.

**Comment by zhuojg** [comment]
> @zhuojg I think 'arXiv` link is OK too and agree with your other comments. This PR has conflicts.

I think there is a conflict because I didn’t have time to merge their PRs today, so conflicts show after merging one.

**Comment by harrywang** [comment]
> > @zhuojg I think 'arXiv` link is OK too and agree with your other comments. This PR has conflicts.
> 
> I think there is a conflict because I didn’t have time to merge their PRs today, so conflicts show after merging one.

that's OK. Just ask them to pull and fix the conflicts and push again.

**Pull request closed without merging**
